package:
  name: hello
  version: 0.0.1
  epoch: 0
  description: "A project that will greet the world infinitely"

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/puerco/hello.git
      expected-commit: fed9b28e2973bee65bcc503c6ab6522e8bfdd3d1
      tag: v${{package.version}}

  - uses: go/build
    with:
      tags: enterprise
      packages: .
      output: hello